{% set name = "flake8-rst-docstrings" %}
{% set version = "0.0.10" %}
{% set sha256 = "009c278460394d7f5a88c9e4da91962e1b7cd6a351913c2c2947b873a4887625" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - flake8 >=3
    - restructuredtext_lint

test:
  commands:
    - "flake8 --version | grep rst-docstrings:"

about:
  home: https://github.com/peterjc/flake8-rst-docstrings
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: 'Extension for flake8 for validating Python docstrings as reStructuredText'
  dev_url: https://github.com/peterjc/flake8-rst-docstrings
  description: |
    This is a flake8 plugin for validating Python docstrings markup as reStructuredText
    (RST) using the Python library docutils, called via Todd Wolfson's package
    restructuredtext-lint.

extra:
  recipe-maintainers:
    - peterjc
